import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BootstrapInit from "@/app/hooks/Bootstrap";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import InitPlugins from "./hooks/InitPlugins";
import Script from "next/script";
import "../../styles/font.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
        <link rel="stylesheet" href="/css/animate.min.css" />
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/magnific-popup.css" />
        <link rel="stylesheet" href="/css/main.css" />
        <link rel="stylesheet" href="/css/meanmenu.css" />
        <link rel="stylesheet" href="/css/metisMenu.css" />
        <link rel="stylesheet" href="/css/nice-select.css" />
        <link rel="stylesheet" href="/css/pristina.font.css" />
        <link rel="stylesheet" href="/css/responsive.css" />
        <link rel="stylesheet" href="/css/slick.css" />
        <link rel="stylesheet" href="/css/theme-default.css" />
        <link rel="stylesheet" href="/css/ui-range-slider.css" />

        <link
          rel="stylesheet"
          href="https://storage.googleapis.com/hrm-assets/jquery.mb.YTPlayer.min.css"
        />

        <Script src="https://code.jquery.com/jquery-3.6.4.min.js"></Script>
        <Script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></Script>

        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></Script>

        <Script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></Script>

        <Script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></Script>

        <Script src="https://cdn.jsdelivr.net/npm/jquery-countdown@2.2.0/dist/jquery.countdown.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/magnific-popup@1.1.0/dist/jquery.magnific-popup.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/gh/pupunzi/jquery.mb.YTPlayer@3.3.9/dist/jquery.mb.YTPlayer.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/metismenu@3.0.7/dist/metisMenu.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/jquery-nice-select@1.1.0/js/jquery.nice-select.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/jquery.scrollup@2.4.1/dist/jquery.scrollUp.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/wowjs@1.1.3/dist/wow.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></Script>

        <Script src="/js/main.js" defer></Script>
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapInit>
          <InitPlugins />
          {children}
        </BootstrapInit>
      </body>
    </html>
  );
}
